import { EquipmentItem, StockLog } from './types';

export const INITIAL_EQUIPMENT_ITEMS: EquipmentItem[] = [
  {
    id: 'item-1',
    name: 'Cabernet Wine Glass (12oz)',
    category: 'Glassware',
    currentStock: 48,
    minThreshold: 24,
    location: 'Main Bar Cabinet A',
    unit: 'pcs',
    unitCost: 75000,
    supplier: 'Premium Glassware Wholesale',
    notes: 'Premium crystal wine glasses. Mandated hand wash only.',
    lastUpdated: '2026-06-12T14:30:00Z',
  },
  {
    id: 'item-2',
    name: 'Glencairn Whiskey Glass',
    category: 'Glassware',
    currentStock: 18,
    minThreshold: 20,
    location: 'Back Bar Display Shelf',
    unit: 'pcs',
    unitCost: 95000,
    supplier: 'Speyside Spirits Supply',
    notes: 'Tasting-grade glasses. Fragile.',
    lastUpdated: '2026-06-12T18:15:00Z',
  },
  {
    id: 'item-3',
    name: 'Amber Glass flip-top Bottle (1L)',
    category: 'Bottles & Decanters',
    currentStock: 12,
    minThreshold: 15,
    location: 'Under-counter Fridge B',
    unit: 'pcs',
    unitCost: 45000,
    supplier: 'EcoPack Bottle Co.',
    notes: 'For house-infused batches and cold water service.',
    lastUpdated: '2026-06-11T09:00:00Z',
  },
  {
    id: 'item-4',
    name: 'Glass Water Decanter (750ml)',
    category: 'Bottles & Decanters',
    currentStock: 25,
    minThreshold: 10,
    location: 'Service Station 2',
    unit: 'pcs',
    unitCost: 120000,
    supplier: 'Premium Glassware Wholesale',
    notes: 'Sleek, handle-less design.',
    lastUpdated: '2026-06-12T11:45:00Z',
  },
  {
    id: 'item-5',
    name: 'Stainless Steel Cocktail Shaker (3-Piece)',
    category: 'Bar Tools',
    currentStock: 8,
    minThreshold: 5,
    location: 'Bar Station 1 & 2',
    unit: 'pcs',
    unitCost: 225000,
    supplier: 'ProBar Distributors',
    notes: 'Cobbler-style shaker, satin finish.',
    lastUpdated: '2026-06-10T16:00:00Z',
  },
  {
    id: 'item-6',
    name: 'Japanese Style Double Jigger',
    category: 'Bar Tools',
    currentStock: 14,
    minThreshold: 6,
    location: 'Main Bar Drawer C',
    unit: 'pcs',
    unitCost: 150000,
    supplier: 'ProBar Distributors',
    notes: '1oz / 2oz capacity with interior markings.',
    lastUpdated: '2026-06-12T08:30:00Z',
  },
  {
    id: 'item-7',
    name: 'Ceramic Espresso Cup (3oz)',
    category: 'Tableware',
    currentStock: 40,
    minThreshold: 30,
    location: 'Espresso Machine Shelf',
    unit: 'pcs',
    unitCost: 80000,
    supplier: 'Clay & Kiln Artisans',
    notes: 'Matte black finish, custom order.',
    lastUpdated: '2026-06-12T10:00:00Z',
  },
  {
    id: 'item-8',
    name: 'Porcelain Latte Bowl (12oz)',
    category: 'Tableware',
    currentStock: 15,
    minThreshold: 20,
    location: 'Espresso Machine Shelf',
    unit: 'pcs',
    unitCost: 90000,
    supplier: 'Clay & Kiln Artisans',
    notes: 'Off-white color, thick wall to preserve temperature.',
    lastUpdated: '2026-06-09T17:00:00Z',
  },
  {
    id: 'item-9',
    name: 'Microfiber Glass Polishing Cloths',
    category: 'Cleaning/Other',
    currentStock: 35,
    minThreshold: 15,
    location: 'Polishing Station B',
    unit: 'pcs',
    unitCost: 25000,
    supplier: 'CleanClean Wholesalers',
    notes: 'Lint-free, essential for wine and cocktail glasses.',
    lastUpdated: '2026-06-13T00:20:00Z',
  }
];

export const INITIAL_STOCK_LOGS: StockLog[] = [
  {
    id: 'log-1',
    itemId: 'item-1',
    itemName: 'Cabernet Wine Glass (12oz)',
    changeType: 'increase',
    amount: 12,
    reason: 'Monthly restock delivery from supplier',
    timestamp: '2026-06-12T14:30:00Z',
  },
  {
    id: 'log-2',
    itemId: 'item-2',
    itemName: 'Glencairn Whiskey Glass',
    changeType: 'decrease',
    amount: 2,
    reason: 'Logged as breakage during shift clean-up',
    timestamp: '2026-06-12T18:15:00Z',
  },
  {
    id: 'log-3',
    itemId: 'item-9',
    itemName: 'Microfiber Glass Polishing Cloths',
    changeType: 'increase',
    amount: 10,
    reason: 'Restocking cleaning cupboard',
    timestamp: '2026-06-13T00:20:00Z',
  },
  {
    id: 'log-4',
    itemId: 'item-3',
    itemName: 'Amber Glass flip-top Bottle (1L)',
    changeType: 'decrease',
    amount: 3,
    reason: 'Retired damaged gaskets',
    timestamp: '2026-06-11T09:00:00Z',
  }
];

export const CATEGORIES = [
  'Glassware',
  'Bottles & Decanters',
  'Bar Tools',
  'Tableware',
  'Cleaning/Other'
];

export const LOCATIONS = [
  'Main Bar Cabinet A',
  'Back Bar Display Shelf',
  'Under-counter Fridge B',
  'Service Station 1',
  'Service Station 2',
  'Bar Station 1 & 2',
  'Main Bar Drawer C',
  'Espresso Machine Shelf',
  'Polishing Station B',
  'Main Storage'
];
